### ISSUE TITLE
Error when using keymaster in react.js component

### ISSUE THREAD

**Issue by Dharmoslap** [madrobby/keymaster#148]
I'm using keymaster.js inside react.js component like this: 

```
componentDidMount: function () {
        key('esc', this.close());
    },
```

And it creates an error:
**Uncaught TypeError: handler.method is not a function, line 106**

**Comment by danott** [comment]
You're calling the function, and passing the result as the argument, instead of passing the function itself.

```javascript
componentDidMount: function () {
  key('esc', this.close.bind(this));
},
```

**Comment by Dharmoslap** [comment]
good, thanks
