### ISSUE TITLE
window.key namespace is too generic, consider moving to window.keymaster

### ISSUE THREAD

**Issue by knutole** [madrobby/keymaster#152]
I've run into problems with other people's libs overwriting the global keyspace with `key` (ie `window.key`).  Since `key` is such a generic name, this problem could be solved with using eg. `keymaster` instead.

**Comment by madrobby** [comment]
Use `noConflict` mode (see the Readme).

**Comment by knutole** [comment]
This means I'd have to use `noConflict` before loading any other libs though.

**Comment by madrobby** [comment]
We can't anticipate every eventuality and the library provides a way to change how you call it via `noConflict`. If you absolutely can't use that, you can fork keymaster and rename the function. 

We won't rename the method just because other libraries don't play nice.
